In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
matr = np.array(my_matrix)

In [8]:
matr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.09241322, 0.28124272, 0.74156456, 0.47058459, 0.73376896])

In [22]:
np.random.rand(5, 5)

array([[0.2001915 , 0.87889749, 0.50301357, 0.7383446 , 0.91738878],
       [0.72412433, 0.00183246, 0.68078503, 0.33567608, 0.75284941],
       [0.76973556, 0.75980058, 0.7276088 , 0.1913386 , 0.09207246],
       [0.16491511, 0.38318517, 0.97556199, 0.88655953, 0.12870489],
       [0.59644955, 0.32377361, 0.16039122, 0.84340659, 0.84610985]])

In [23]:
np.random.randn(5)

array([ 0.43104418, -0.20970613,  0.1775941 ,  0.4053607 ,  0.04968038])

In [24]:
np.random.randn(5, 5)

array([[-0.58391089,  0.56056185,  0.778906  ,  0.79189338, -0.89774164],
       [-0.5091797 , -0.12750245,  0.56736754,  1.26841302,  0.20707163],
       [-0.10841661, -0.35309518, -0.24168392, -0.34895783, -0.21993732],
       [ 2.62582229,  0.82569949,  0.42849106,  0.17060122, -1.06457231],
       [-0.94682592,  2.58730191,  1.01619188, -1.02251799, -1.34393555]])

In [25]:
np.random.randint(1, 100)

77

In [26]:
np.random.randint(1, 100, 10)

array([43, 57,  5, 57, 90, 37, 70, 34, 44, 13])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0, 50, 10)

In [30]:
ranarr

array([ 1,  9, 43, 29, 11,  2,  5, 27, 23, 25])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

43

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmax()

2

In [36]:
ranarr.argmin()

0

In [37]:
arr.shape

(25,)

In [38]:
ranarr.shape

(10,)

In [39]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.shape

(25,)

In [41]:
arr.dtype

dtype('int64')

## Indexing and Selection

In [43]:
arr = np.arange(0, 11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[8]

8

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# broadcasting

In [51]:
arr[0:5] = 99

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [64]:
arr[0:5] = [0,1,2,3,4]

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
slice_arr = arr[0:5]

In [60]:
slice_arr

array([0, 1, 2, 3, 4])

In [61]:
slice_arr[:] = 99

In [62]:
slice_arr

array([99, 99, 99, 99, 99])

In [63]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [65]:
slice_arr = arr[0:5].copy()

In [66]:
slice_arr

array([0, 1, 2, 3, 4])

In [67]:
slice_arr[:] = 99

In [68]:
slice_arr

array([99, 99, 99, 99, 99])

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Array

In [71]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [72]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr_2d[0][0]

1

In [74]:
arr_2d[0,0]

1

In [77]:
arr_2d[1][1]

5

In [79]:
arr_2d[2,2]

9

In [80]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [91]:
arr_2d[:2][:,1:]

array([[2, 3],
       [5, 6]])

In [92]:
arr_2d[:2][:][1:]

array([[4, 5, 6]])

In [94]:
arr_2d = np.arange(50).reshape(5,10)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [9]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [10]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
1/0

ZeroDivisionError: division by zero

In [12]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

## Universal Array Functions

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.max(arr)

10

In [22]:
arr.max()

10

In [24]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [26]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])